name:                flatbuffers
version:             0.1.0.0
#synopsis:
#description:
homepage:            https://github.com/dcastro/haskell-flatbuffers#readme
license:             BSD3
author:              Diogo Castro
maintainer:          dc@diogocastro.com
copyright:           2017 Diogo Castro
category:            Web

extra-source-files:
- README.md
- cbits/cbits.c

ghc-options:
  - -fdefer-typed-holes
  # - -Wall
  - -Wincomplete-record-updates
  - -Wredundant-constraints
  - -O1

dependencies:
  - base >= 4.7 && < 5
  - bytestring
  - text
  - mtl
  - containers
  - megaparsec
  - parser-combinators
  - binary
  - scientific
  - template-haskell
  - filepath
  - directory
  - text-manipulate
  - deepseq

library:
  source-dirs:      src
  c-sources:
    - cbits/cbits.c

tests:
  test:
    main: Spec.hs
    source-dirs: test/
    dependencies:
    - flatbuffers
    - hspec
    - HUnit
    - hspec-megaparsec
    - hedgehog
    - hw-hspec-hedgehog
    - http-client
    - http-types
    - aeson
    - aeson-pretty
    - raw-strings-qq
    - utf8-string
    - process
    - pretty-simple
    - th-pprint

benchmarks:
  criterion-bench:
    main: CriterionMain.hs
    source-dirs: bench/
    other-modules:
      - Types
      - CriterionBench.Encode
      - CriterionBench.EncodeVectors
      - CriterionBench.DecodeVectors
    dependencies:
      - flatbuffers
      - criterion
      - vector
      - aeson
    ghc-options:
      - -threaded
      - -rtsopts
