name:                flatbuffers
version:             0.1.0.0
#synopsis:
#description:
homepage:            https://github.com/dcastro/haskell-flatbuffers#readme
license:             BSD3
author:              Diogo Castro
maintainer:          dc@diogocastro.com
copyright:           2017 Diogo Castro
category:            Web
extra-source-files:
- README.md

ghc-options:
  - -fdefer-typed-holes
  # - -Wall
  - -Wincomplete-patterns
  - -Wincomplete-record-updates
  - -Wtabs
  - -Wno-unticked-promoted-constructors

dependencies:
  - base >= 4.7 && < 5
  - bytestring
  - utf8-string
  - text
  - mtl
  - transformers
  - containers
  - lens
  - megaparsec
  - parser-combinators
  - binary
  - hw-int
  - safe-exceptions
  - tagged

library:
  source-dirs:      src

tests:
  integration:
    main: Spec.hs
    source-dirs: test/integration
    dependencies:
    - flatbuffers
    - hspec
    - http-client
    - http-types
    - aeson
    - aeson-pretty
  unit:
    main: Spec.hs
    source-dirs: test/unit
    dependencies:
    - flatbuffers
    - hspec
    - hspec-megaparsec
    - hedgehog
    - hw-hspec-hedgehog

