name:                flatbuffers
version:             0.1.0.0
#synopsis:
#description:
homepage:            https://github.com/dcastro/haskell-flatbuffers#readme
license:             BSD3
author:              Diogo Castro
maintainer:          dc@diogocastro.com
copyright:           2017 Diogo Castro
category:            Web
extra-source-files:
- README.md

ghc-options:
  - -fdefer-typed-holes
  # - -Wall
  - -fwarn-incomplete-patterns
  - -fwarn-tabs
  - -Wno-unticked-promoted-constructors

dependencies:
  - base >= 4.7 && < 5
  - safe-exceptions
  - bytestring
  - utf8-string
  - text
  - mtl
  - containers
  - lens


library:
  source-dirs:      src

tests:
  test:
    main: Spec.hs
    source-dirs: test/integration
    dependencies:
    - flatbuffers
    - hspec
    - http-client
    - http-types
    - aeson
    - aeson-pretty

