name:                flatbuffers
version:             0.1.0.0
homepage:            https://github.com/dcastro/haskell-flatbuffers
github:              dcastro/haskell-flatbuffers
license:             BSD3
author:              Diogo Castro
maintainer:          dc@diogocastro.com
copyright:           2019 Diogo Castro
category:            Data, Serialization, Network
tested-with:         GHC == 8.6.5

synopsis:            Haskell implementation of the FlatBuffers protocol.
description:
  Haskell implementation of the FlatBuffers protocol,
  a protocol for memory efficient serialization, originally designed by Google.


extra-source-files:
  - README.md
  - cbits/cbits.c

extra-doc-files:
  - README.md

ghc-options:
  - -Wall
  - -Wno-name-shadowing
  - -Wincomplete-record-updates
  - -Wredundant-constraints

dependencies:
  - base >= 4.7 && < 5
  - bytestring
  - text
  - mtl
  - containers
  - megaparsec
  - parser-combinators
  - binary
  - scientific
  - template-haskell
  - filepath
  - directory
  - text-manipulate

library:
  source-dirs:      src
  c-sources:
    - cbits/cbits.c

tests:
  test:
    main: Spec.hs
    source-dirs: test/
    dependencies:
    - flatbuffers
    - hspec
    - hspec-core
    - hspec-expectations-pretty-diff
    - HUnit
    - hspec-megaparsec
    - hedgehog
    - hw-hspec-hedgehog
    - http-client
    - http-types
    - aeson
    - aeson-pretty
    - raw-strings-qq
    - utf8-string
    - process
    - th-pprint

benchmarks:
  criterion-bench:
    main: Main.hs
    source-dirs: bench/
    dependencies:
      - flatbuffers
      - criterion
      - vector
      - aeson
    ghc-options:
      - -threaded
      - -rtsopts
